name: safealert
description: Universal panic button & security response platform
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  go_router: ^14.2.8
  flutter_screenutil: ^5.9.3

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3

  # Push notifications + vibration (работает без платного аккаунта)
  flutter_local_notifications: ^17.2.2

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1

  # Localization
  easy_localization: ^3.0.7

  # State management & utils
  riverpod: ^2.5.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/branding/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/branding/app_logo.png"
  min_sdk_android: 21
